fix thumbnail script for Linux

diff --git a/thumbnail b/thumbnail
--- a/thumbnail
+++ b/thumbnail
@@ -5,6 +5,11 @@ usage() {
 	exit 1
 }
 
+err() {
+	echo "thumbnail:" "$@" >&2
+	exit 1
+}
+
 mkthumbdir() {
 	mkdir -p "$thumbdir"
 }
@@ -52,13 +57,22 @@ esac
 
 umask 077
 
+if type md5 >/dev/null
+then
+	md5cmd="md5"
+elif type md5sum >/dev/null
+then
+	md5cmd="md5sum"
+else
+	err "could not find md5sum command"
+fi
 origfile="$1"
 thumbsize=128
 thumbdir="${THUMBDIR:-"${CACHEDIR:-${XDG_CACHE_HOME:-"$HOME/.cache"}}/thumbnails/normal"}"
 canonpath="$(readlink -f "$origfile" 2>/dev/null)" || geticonpng error
-md5sum="$(echo "$canonpath" | md5)"
+hash="$(echo "$canonpath" | "$md5cmd")"
 mtime="$(stat -f %m "$canonpath")"
-thumbfile="$thumbdir/$md5sum.png"
+thumbfile="$thumbdir/$hash.png"
 extension="$(getextension "$canonpath")"
 
 mkthumbdir
